framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: '%env(REDIS_PREFIX)%'

        # Redis
        app: cache.adapter.redis_tag_aware
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(int:REDIS_PORT)%'

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
